### ISSUE TITLE
Single generic class singleton retreival should get injected

### ISSUE THREAD

**Issue by dave08** [rewe-digital/katana#11]
Currently, if one tries to declare a single singleton of a generic class without naming it, and runs `get()`, type erasure will prevent it to be resolved. The expected behavior is that if there is only one such declaration, it should be injected. If there are many, there should be an error (even if their type parameters are different) unless they are all named. If the type params don't match what the get() is injecting to, then it should just be considered if it will only crash on use (not so good), or if there is a way to catch and report this beforehand.

**Comment by svenjacobs** [comment]
Hi Dave, thanks for the report. I tried to reproduce this behavior with the following test

```kotlin
it("should work for single generic declaration as transitive dependency") {
    class MyDependency(val list: MutableList<String>)

    val module = Module {

        singleton { mutableListOf("Hello", "World") }

        factory { MyDependency(get()) }

        factory(name = "listInvalidator") { get<MutableList<String>>().clear() }
    }

    val component = Component(modules = listOf(module))

    val myDependency by component.inject<MyDependency>()
    component.injectNow<Unit>(name = "listInvalidator")
    myDependency shouldBeInstanceOf MyDependency::class.java
    myDependency.list shouldBeInstanceOf List::class.java
    myDependency.list shouldHaveSize 0
}
```

but the test works.

Which version of Katana are you using? Can you please provide a minimal example project reproducing this issue?

**Comment by dave08** [comment]
I'm using 1.6.0 in that particular project, maybe it's only a problem with that version?

**Comment by svenjacobs** [comment]
If possible please try to reproduce this issue with the newest version 1.8.3.

**Comment by svenjacobs** [comment]
Closing issue. If this still occurs with latest version of Katana, please let me know.
