### ISSUE TITLE
Rename injectNow() to get()

### ISSUE THREAD

**Issue by svenjacobs** [rewe-digital/katana#16]
Think about renaming `injectNow()` to `get()`.

**Comment by dave08** [comment]
Why? I think `injectNow` is pretty clear? And `get()` could be pretty common in class code (like the operator overload and in collections)... although usually collections don't get injected. This is also a breaking change that could involve quite a bit of refactoring for some...

**Comment by svenjacobs** [comment]
I'm not really satisfied with the adverb `now` in `injectNow()`. Do users know `now` from other frameworks? I don't think so.

I don't see a conflict when using `get()` like

```
private val someDependency: SomeDependency = component.get()
```

Can you please show examples of where you think this could be problematic?

**Comment by dave08** [comment]
Well, when you have a class implementing `KatanaTrait` (it might seem a bit contrived, but I've encountered things I didn't think I would do when I migrated...):

```
class SomeClass : KatanaTrait {
	private val someDependency: SomeDependency = get()

	...

	operator fun get() = ...
}
```

Also, the main problem I have is that it might be a bit funny understanding what you're getting... in the context of a class with other things that are being gotten `inject` is clear whereas `get()` is a bit general and could be interpreted as something else...
