### ISSUE TITLE
JCenter sunsetting

### ISSUE THREAD

**Issue by carltonwhitehead** [rewe-digital/katana#23]
JCenter is sunsetting on May 1, 2021, per https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Katana is published on JCenter, and not on Maven Central, so anyone using it will be affected.

Knowing that Katana is not actively developed anymore, I'm not sure anyone has any serious expectation that the library would be re-published elsewhere.

What are your thoughts on publishing Katana on Maven Central or another channel?

**Comment by svenjacobs** [comment]
Thanks for letting me know. Since Katana is still used by a few projects, I will investigate what is necessary to publish to Maven Central.

**Comment by svenjacobs** [comment]
After a lot of sweating & swearing 😉 I finally managed to publish Katana to Maven Central via Sonatype OSSRH. The latest version `1.14.0` is now available on Central. From now on any future versions will only be published to Central and not to JCenter.
