### ISSUE TITLE
katana-androidx-viemodel: Couldn't inline method call

### ISSUE THREAD

**Issue by svenjacobs** [rewe-digital/katana#7]
Since updating Katana to Kotlin 1.3.30 (Katana version 1.6.1), usages of `katana-androidx-viemodel` inline functions result in a compiler exception `couldn't inline method call`. This seems to be a compiler issue and is tracked [here](https://youtrack.jetbrains.com/issue/KT-31264).

**Comment by svenjacobs** [comment]
It seems that not the Kotlin version but the Android plugin is the reason for this bug. After downgrading the Android plugin to version 3.3.2, usages of the inline functions work again. However this should just be a temporary workaround. I leave this ticket open until a solution is found.

The Katana version where this has been "fixed" is 1.6.3.

**Comment by LouisCAD** [comment]
Did you try with AGP 3.4.1 and with 3.5.0-beta01?

**Comment by svenjacobs** [comment]
> Did you try with AGP 3.4.1 and with 3.5.0-beta01?

3.4.1 yes, 3.5.0-beta01 no

**Comment by svenjacobs** [comment]
This still fails with AGP 3.5.0 and Kotlin 1.3.50

**Comment by svenjacobs** [comment]
Still an issue with AGP 3.6.1 and Kotlin 1.3.70

**Comment by svenjacobs** [comment]
Actually it seems like ProGuard plays a role in this. When ProGuard is disabled for the library artifacts, the error does not occur even with latest AGP and Kotlin versions.

**Comment by svenjacobs** [comment]
ProGuard has been disabled in the project. Closing this ticket.
