### ISSUE TITLE
Add singletonSet to module DSL

### ISSUE THREAD

**Issue by dave08** [rewe-digital/katana#8]
Often we have a pattern in Android to have a list of Intents that can be processed by an implementation of:
```kotlin
interface TaskHandler {
	fun canHandle(action: String): Boolean

	fun run()
}
```
And we need to instantiate these classes with Katana, and then put them into one big list/set and then run:
```kotlin
injectNow<Set<TaskHandler>>().first { it.canHandle(intent.action) }.run()
```
Currently this can only be done by tagging (some implementations are registered multiple times with different constructor params) each singleton/factory and then using `get<TaskImplementation>(TaskTag)` to build the list/set in one big `singleton<Set<TaskHandler>> { }`, this is very tedious and error-prone.

The proposition is to have a `singletonSet<TaskHandler> { TaskOne(get(), get()) }` that will just accumulate all those instances into one set that can be retrieved with `get<Set<TaskHandler>>()` since the instances themselves are of no real interest. Any request for an individual instance could be an error that it needs to be get as a set.

I'm still not sure about whether this should only be a Set or maybe a List and Map too. A map could avoid instantiating all the classes, and just have the intent's action as the key and the handler for it as the value.

This feature might not be only for Android, but in Android there's another little point to consider if the intent's other properties are needed.

**Comment by svenjacobs** [comment]
In order to support this, Katana could provide a new DSL of the kind:

```kotlin
set<MyClass> { 
  factory { MyClassImpl1() }
  singleton { MyClassImpl2() }
}
```

where `set` declares a "binding context". Every binding inside a context contributes to a `Set`. Contributions should be possible across multiple modules.

**Comment by svenjacobs** [comment]
@dave08 It took some time but this feature has now been implement in version 1.8.0 :)

**Comment by dave08** [comment]
Thanks @svenjacobs! :+1:
